### ISSUE TITLE
Using multiple sources breaks output

### ISSUE THREAD

**Issue by jacobisaliveandwell** [asyncon/setuptools-pipfile#2] opened 2020-08-04 02:07 UTC
I'm using multiple sources and specifying them within the config, which is resulting in odd version specifications:

```toml
[[source]]
# PyPi Repository
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
boto3 = {version = "*", index = "pypi"}
```

```python
from pprint import pprint
pprint(vars(distribution))
```

```plain
'install_requires': ['boto3@ https://pypi.org/simple/boto3/'],
```

It looks like `install_requires` [shouldn't have any index related metadata in it](https://packaging.python.org/discussions/install-requires-vs-requirements/), and that should just be `['boto3']`.

**Comment by jacobisaliveandwell** [comment] 2020-08-04 02:11
It looks like `install_requires` [shouldn't have any index related metadata in it](https://packaging.python.org/discussions/install-requires-vs-requirements/)

**Comment by jacobisaliveandwell** [comment] 2020-08-04 03:59
Looks like this breaks `test_requires too. I can't get the format being passed to setuptools, but getting this error:

```plain
error in python_example setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Invalid URL given
```

**Comment by asyncon** [comment] 2020-08-04 16:38
This is by design in order to replicate the explicit index binding specified in the Pipfile.

Packages by default are not assigned to an index and will get whatever default index is configured for pip.

A flag needs to be added to disable the explicit index binding behaviour.

Dependency links should continue to be populated.

**Comment by jacobisaliveandwell** [comment] 2020-08-04 17:19
@asyncon No sure I understand your reply. This currently breaks `build` and `*dist` commands.

Do you have documentation on the syntax allowed for `install_requires` and `test_requires`? I don't think it accepts an at (`@`) with a space (` `) following.

**Comment by asyncon** [comment] 2020-08-04 22:59
The main way to not have an index url assigned to a dependency in setuptools is to not assign it in your `Pipfile`. Dependencies do not require an index to be specified. Development of an option to disable index url specifiers is in progress.

The dependency specification is [pep508](https://www.python.org/dev/peps/pep-0508/#whitespace) and permits whitespace between tokens including the `@` url specifier.

`tests_require` is something that should be avoided as the test command has been [deprecated](https://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite) and is only included for completeness.

Also setuptools-pipfile shouldn't be in your Pipfile. Add it to either setup.py, setup.cfg, or pyproject.toml.

**Comment by asyncon** [comment] 2020-08-05 11:06
Now having replicated the issue the best course of action seems to be setting the default behaviour to not include index urls in `install_requires` and `tests_require`.

[pep440](https://www.python.org/dev/peps/pep-0440/#direct-references) specifies expected behaviour regarding direct references.

The question that remains is should index urls have their basic auth removed if interpolation is enabled?

**Closed** 2020-08-05 14:55 UTC
